# Generated by Django 6.0.3 on 2026-05-12 21:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Creature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "type1",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("fire", "Fuego"),
                            ("water", "Agua"),
                            ("electric", "Eléctrico"),
                            ("grass", "Planta"),
                            ("ice", "Hielo"),
                            ("fighting", "Lucha"),
                            ("poison", "Veneno"),
                            ("ground", "Tierra"),
                            ("flying", "Volador"),
                            ("psychic", "Psíquico"),
                            ("bug", "Bicho"),
                            ("rock", "Roca"),
                            ("ghost", "Fantasma"),
                            ("dragon", "Dragón"),
                            ("dark", "Siniestro"),
                            ("steel", "Acero"),
                            ("fairy", "Hada"),
                        ],
                        max_length=20,
                        verbose_name="Tipo Principal",
                    ),
                ),
                (
                    "type2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("fire", "Fuego"),
                            ("water", "Agua"),
                            ("electric", "Eléctrico"),
                            ("grass", "Planta"),
                            ("ice", "Hielo"),
                            ("fighting", "Lucha"),
                            ("poison", "Veneno"),
                            ("ground", "Tierra"),
                            ("flying", "Volador"),
                            ("psychic", "Psíquico"),
                            ("bug", "Bicho"),
                            ("rock", "Roca"),
                            ("ghost", "Fantasma"),
                            ("dragon", "Dragón"),
                            ("dark", "Siniestro"),
                            ("steel", "Acero"),
                            ("fairy", "Hada"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo Secundario",
                    ),
                ),
                (
                    "hp",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ],
                        verbose_name="Puntos de Salud",
                    ),
                ),
                (
                    "attack",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ],
                        verbose_name="Ataque",
                    ),
                ),
                (
                    "defense",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ],
                        verbose_name="Defensa",
                    ),
                ),
                (
                    "speed",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ],
                        verbose_name="Velocidad",
                    ),
                ),
                (
                    "sp_attack",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ],
                        verbose_name="Ataque Especial",
                    ),
                ),
                (
                    "sp_defense",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ],
                        verbose_name="Defensa Especial",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="URL de Imagen"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Criatura",
                "verbose_name_plural": "Criaturas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("fire", "Fuego"),
                            ("water", "Agua"),
                            ("electric", "Eléctrico"),
                            ("grass", "Planta"),
                            ("ice", "Hielo"),
                            ("fighting", "Lucha"),
                            ("poison", "Veneno"),
                            ("ground", "Tierra"),
                            ("flying", "Volador"),
                            ("psychic", "Psíquico"),
                            ("bug", "Bicho"),
                            ("rock", "Roca"),
                            ("ghost", "Fantasma"),
                            ("dragon", "Dragón"),
                            ("dark", "Siniestro"),
                            ("steel", "Acero"),
                            ("fairy", "Hada"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("physical", "Físico"),
                            ("special", "Especial"),
                            ("status", "Estado"),
                        ],
                        max_length=10,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "power",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(255)],
                        verbose_name="Poder (daño)",
                    ),
                ),
                (
                    "accuracy",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Precisión (%)",
                    ),
                ),
                (
                    "pp",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name="PP (Usos)",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Movimiento",
                "verbose_name_plural": "Movimientos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CreatureMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_learned",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Nivel que aprende",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.creature",
                        verbose_name="Criatura",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.move",
                        verbose_name="Movimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Criatura",
                "verbose_name_plural": "Movimientos de Criaturas",
                "ordering": ["level_learned", "move__name"],
                "unique_together": {("creature", "move")},
            },
        ),
        migrations.AddField(
            model_name="creature",
            name="moves",
            field=models.ManyToManyField(
                through="myapp.CreatureMove",
                to="myapp.move",
                verbose_name="Movimientos",
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre del Equipo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Público"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrenador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Esperando Oponente"),
                            ("active", "En Combate"),
                            ("finished", "Finalizado"),
                            ("abandoned", "Abandonado"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_turn",
                    models.PositiveIntegerField(default=1, verbose_name="Turno Actual"),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("player1", "Jugador 1"),
                            ("player2", "Jugador 2"),
                            ("draw", "Empate"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Ganador",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado"
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_player1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Jugador 1",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_player2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Jugador 2",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_team1",
                        to="myapp.team",
                        verbose_name="Equipo Jugador 1",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_team2",
                        to="myapp.team",
                        verbose_name="Equipo Jugador 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combate",
                "verbose_name_plural": "Combates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamCreature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Posición en el equipo",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.creature",
                        verbose_name="Criatura",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.team",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criatura en Equipo",
                "verbose_name_plural": "Criaturas en Equipos",
                "ordering": ["position"],
                "unique_together": {("team", "position")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="creatures",
            field=models.ManyToManyField(
                through="myapp.TeamCreature",
                to="myapp.creature",
                verbose_name="Criaturas",
            ),
        ),
        migrations.CreateModel(
            name="BattleTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turn_number",
                    models.PositiveIntegerField(verbose_name="Número de Turno"),
                ),
                (
                    "player1_action",
                    models.CharField(max_length=200, verbose_name="Acción Jugador 1"),
                ),
                (
                    "player1_target",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Objetivo Jugador 1"
                    ),
                ),
                (
                    "player2_action",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Acción Jugador 2"
                    ),
                ),
                (
                    "player2_target",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Objetivo Jugador 2"
                    ),
                ),
                ("turn_result", models.TextField(verbose_name="Resultado del Turno")),
                (
                    "damage_dealt_p1",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Daño Causado por P1"
                    ),
                ),
                (
                    "damage_dealt_p2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Daño Causado por P2"
                    ),
                ),
                (
                    "p1_creature_hp",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="HP Criatura P1"
                    ),
                ),
                (
                    "p2_creature_hp",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="HP Criatura P2"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.battle",
                        verbose_name="Combate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno de Combate",
                "verbose_name_plural": "Turnos de Combate",
                "ordering": ["battle", "turn_number"],
                "unique_together": {("battle", "turn_number")},
            },
        ),
    ]
