# Generated by Django 6.0.3 on 2026-05-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("team", "Análisis de Equipo"),
                            ("battle", "Recomendación de Combate"),
                            ("general", "Consejo General"),
                        ],
                        max_length=20,
                        verbose_name="Contexto",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="Datos de Entrada")),
                ("recommendation", models.TextField(verbose_name="Recomendación")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.creature",
                        verbose_name="Criatura Relacionada",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.team",
                        verbose_name="Equipo Relacionado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de IA",
                "verbose_name_plural": "Mensajes de IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
