# Generated by Django 6.0.3 on 2026-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_aimessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="creature",
            name="pokemon_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Identificador en PokéAPI (vacío para criaturas custom).",
                null=True,
                unique=True,
                verbose_name="ID PokéAPI",
            ),
        ),
    ]
